# Generated by Django 6.0.4 on 2026-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='style_theme',
            field=models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень')], default='spring', max_length=20, verbose_name='Стиль оформления'),
        ),
    ]
