# Generated by Django 6.0.4 on 2026-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Фото для фона главной', 'verbose_name_plural': 'Фото для фона главной'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Изображение фона'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте?'),
        ),
    ]
