# Generated by Django 6.0.4 on 2026-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_banner_options_remove_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_prompt',
            field=models.TextField(blank=True, verbose_name='Промпт для AI (обработка фото)'),
        ),
    ]
